version: "{build}"

build: off
deploy: off

install:
  - cd %LOCALAPPDATA%
  - ps: (New-Object Net.WebClient).DownloadFile("https://atom.io/download/windows_zip?channel=stable", "$(pwd)\atom-windows.zip")
  - 7z -y x atom-windows.zip > nul
  - SET PATH=%LOCALAPPDATA%\Atom\resources\app\apm\bin;%LOCALAPPDATA%\Atom\;%PATH%
  - apm --version
  - atom --version

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - apm clean
  - apm install
  - powershell assets\appveyor.ps1
